name: "saas_revenue_customer_health_platform"
version: "1.0.0"
config-version: 2

profile: "saas_revenue_customer_health_platform"

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  saas_revenue_customer_health_platform:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table